server:
  port: 8086
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  elasticsearch:
    rest:
      uris: http://192.168.56.10:9200
  jackson:
    default-property-inclusion: non_null
  rabbitmq:
    host: 192.168.56.10
    virtual-host: /qiao
    username: qiao
    password: qiao