server:
  port: 8091
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 192.168.56.10
  rabbitmq:
    host: 192.168.56.10
    virtual-host: /qiao
    username: qiao
    password: qiao
gmall:
  jwt:
    pubKeyPath: D:\\rsa\\rsa.pub # 公钥地址
    cookieName: GMALL_TOKEN
    userKey: user-key
alipay:
  app_id: 2016102200739985
  merchant_private_key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCm7wzghZ7MYIGREShv5SwHMXpgLh4prtPbFMLpzAoNUWYHtJ9vJz00QSeVyRWybb4vDUx0gRfLL20evpQBt9906V3p8tJ47yhRaWLUrd/ukkNhYU7QWUQj9S41cQw2CL2LS1IZ5ji5Rl8jBXGl3j2zhQgggdpKahQVpcHPnLWFGuDfEb7s5vIuGXlpaZnQ/PMaz9FPi3kfzzWOLXPOxjrN1l3rbQ788G2u5pD+hfIFpAJ6b7nzCqKMvEpac3fd35C/ea0Yu5yWjDk0lfySCxoDJg5sUS7nx8UCRxrkzVG8JvtjvCpM5fGf7qEtQvKVc07TBeUcyvORCJUqw11WLFPDAgMBAAECggEAM0JcVeUx6dgIcR8vp4xbhKnwxe/jWzFP5InvgBMjUwuXpO4Vtu/5nz4ShbAFdZC1QYV34J5zS/T4MOScVhq8Bw5RxDDH6FKnsrgFnQD3Li7DefeDV/7RKalz0v0vnrf4W/l48HL9IAc3120ohKJFmAZVhIXbHdaM7EjFxpZ8Nq6XBKiJwM7/vm3Hk4hOZ2OGOLKzuAuWhpP47lO+sjfktDT/WEyJzT33OwbY7YpkwyS6DaJ/OuQ2m7ol+sDN7Gk+3zDnHf0pY6niaOfQibjs3WINcPOL+dEtKTfaxitRtx4csZM1uHyl6cz3JnA/Tw3RPjalg+/nlR7NV6nkqpVLIQKBgQDbwjVv1zBLFJWjTgRgcP1bEUhD5vZAl1M0ht4ZV38s9bHHg4Cz8NkmX78jD4btvAydwVcxpWnLvMkWRcsRUFiRuEz3v8W5sWGK62/SFdWMWqfitv4yEeidiNbocKQ3g8zLQS3qalhRzM8aTbwmuN+Klkv+jzWd7nUZlD9ZUtFU1wKBgQDCdq1p4kJ58mqSdv0xCKfzRTSN7u1E6+GGXhxAl3Ra4dcYmlnvJj+fu94oA2jTxmRkVjhgCTIYZzhVcxBmYn1WVx35MM8expgobIlSTudCkvuDpj/x7cXToxmKdU3ktaHV+LrVVi7/3Q9VXr7ZTdTyIniehMMi/e8yO2QoY7Su9QKBgQDZY051KkutmdlEyGJv/JXDxl7UPN8QmiFG7rs6GmHF2e5ZTO6+Edzdpw1u42c4OTPJwn48sELttfy9uaDdqbtTuxr4YY542M2DHM9q5QpwYyV8kkT2xtxzKfBd0z+/YvPthLalEzn3AUFF5evf6jXH5FGcqZICfub7vLjF5bUJ1QKBgBDc367F2wPeHJW00cHVwVKcFrGUHWkTl0vij0qel41l9hQBFnlhdLTyQpJvsUBj/MKio2LYiUqKcN0gDDUEp1+8UDISpHNDv2AKAWJsyyr/ueWxnevptXTjuMxD3cxOX8lBN1pWjd7MGY9Klvwa/rM8f/8m/hDjukE92zKRatKdAoGALevVRwSgWa70b6kTBuU9kPIXFNP1JWs/mDef6fpuVV0kRA1s59brtDC8HM0OhEIykC0bClfvle0mlDjsWo5IgCE5kl6EwgORz+qX+qXABIBByVwuxdfU+GhQpQrThOKpkuS6eeTqkW+O5iMqMfODDq3wyy769pagRvKQVhF7a9o=
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnJVs9f/ZHmUhHQD3Q+p8fgPhvTy4Lyl+/i8ePy660w3WKNrERcPD3FEuZ8U56V0O9ty509EdbIQIqZLLA1OKGMY45FNvGFc8GWoSP5899+hQjyuwDkjLBQTzWQj0hBHelI0radPTYR7qwdUTIn8cTdOJu9Fp7+j3UglWCxhJ9N4qIM5T2kK7KAd79SoiMnR4DGiGyiyHScXOWb6NSvfpBymgUDAU1IrqP28Cj+oBHhgo5x3kbGpCdeKsLyCIt7DZ+zpvy1JXJu/Zx27Nv9RU9M5njBw0atDx44BGqqEyyl5OPttTHpcbmzd8YA1FbIajc8tTQqne+XIBq6I3TQQTkQIDAQAB
  notify_url: http://9glldacce2.52http.net/api/order/pay/success
  return_url: http://www.baidu.com
  sign_type: RSA2
  gatewayUrl: https://openapi.alipaydev.com/gateway.do