server:
  port: 8091
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 192.168.56.10
  rabbitmq:
    host: 192.168.56.10
    virtual-host: /qiao
    username: qiao
    password: qiao
gmall:
  jwt:
    pubKeyPath: D:\\rsa\\rsa.pub # 公钥地址
    cookieName: GMALL_TOKEN
    userKey: user-key